# Generated by Django 4.2.11 on 2024-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('Like', models.IntegerField()),
                ('share', models.IntegerField()),
                ('Save', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.IntegerField()),
                ('CourseName', models.TextField()),
                ('Language', models.TextField()),
                ('Category', models.TextField()),
                ('duration', models.TextField()),
                ('CoursePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternId', models.IntegerField()),
                ('InternTitle', models.TextField()),
                ('InternCategory', models.TextField()),
                ('InternDur', models.TextField()),
                ('INternCompamy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.IntegerField()),
                ('ProjectTitle', models.TextField()),
                ('ProjectCategory', models.TextField()),
                ('ProjectDura', models.IntegerField()),
                ('ProjectDec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('Username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('catogery', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
