# Generated by Django 4.2.11 on 2024-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReguserRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('Username', models.TextField()),
                ('Industry', models.TextField()),
                ('Domain', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reguserteach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('Username', models.TextField()),
                ('TeachingExp', models.TextField()),
                ('TeachingDomain', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Reguser',
            new_name='Reguserstud',
        ),
        migrations.RenameField(
            model_name='reguserstud',
            old_name='catogery',
            new_name='EducationLevel',
        ),
    ]
